sudo: required

env:
    - ARCH_TRAVIS_VERBOSE=1

arch:
    repos:
        - xyne-any=http://xyne.archlinux.ca/repos/xyne
    packages:
        # C/C++
        - gcc
        - clang
        - tcc
        # Python
        - pypy3
        # Java
        - jdk8-openjdk
        # Vala
        - vala
        # VisualBasic/C#
        - mono
        # common
        - time
        # stuff...
        - reflector
        - archey3-git
    script:
        - "sudo archey3"
        - "reflector --verbose -l 20 --sort rate -p https"
        - "ls -la"
        - "pacman -Q"
        - "./script.sh"
script:
    - "bash ./arch-travis.sh"
