sudo: required
language: generic

arch:
    packages:
        # C/C++
        - gcc
        - clang
        - tcc
        # Python
        - pypy3
        # Java
        - jdk8-openjdk
        # Vala
        - vala
        # VisualBasic/C#
        - mono
        - mono-basic
        # JavaScript
        - nodejs
        # D
        - gdc
        - ldc
        - dmd
        # Swift
        - swift-bin
        - icu55
        - libbsd
        - libedit
        - libtinfo
        - libutil-linux
        - libxml2
        - ncurses5-compat-libs
        - python2
        - python2-six
        # common
        - time
        # stuff...
        - archey3-git
    script:
        - "sudo archey3"
        - "pacman -Q"
        - "./script.sh"
script:
    - "bash ./arch-travis.sh"
branches:
    except:
        - pushes
