sudo: required
language: generic

arch:
    packages:
        # C/C++
        - gcc
        - clang
        - tcc
        # Python
        - pypy3
        # Java
        - jdk8-openjdk
        # Vala
        - vala
        # VisualBasic/C#
        - mono
        - mono-basic
        # JavaScript
        - nodejs
        # D
        - gdc
        - ldc
        - dmd
        # Swift
        - swift-language-git
        - icu
        - libbsd
        - libedit
        - libxml2
        - ncurses
        - python2
        - swig
        - clang
        - cmake
        - git
        - ninja
        # common
        - time
        # stuff...
        - archey3-git
    script:
        - "sudo archey3"
        - "pacman -Q"
        - "./script.sh"
script:
    - "bash ./arch-travis.sh"
branches:
    except:
        - pushes
